language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: XJttkunlqw7tg5pi8i9vkE49QFwZnW0EPE4BnNQHKMQm3wcW9wC3bOKH9S+iI/jsWHcNrypiPdYhPAUFcbozbkh2AjK9mU35183psmS/8/WpmrndQ2/3K5INEq92L6yUfeYsK1OJeUXRrLHTlNZoTlQQHAdDKNmv9lyiPMEYud/dkYZ878OuOHcS/7tAcCdoPa9P5PYn+2aRjwt4BuQIJso+WPKXuK/YXKh8KG1KshIHuli6NjTnmxSSedjBl4dpFciuYNVPGnVnoaTr+AYqQHeyu+LyjYWIxrhLH5vN8xtCIpTtw4EOuui+WhrrzINi7Q32okTd3Hx7wPzwuWs2lpQQ8Z4q/DDPESgbo68cXmsPo+HsvWu39Akvh1iUh5XLpQhk3EC9KtoELjTfD7W8+vMahwWr8Cb2wzjs7yywsA6LGrhFxjKKKbehyRQdUdVDrUDmCGXcb/m1XVEnukRxQLP7UzEvG5QVyL2ZIrNOI8qpiw5LSY+XeVD23X+2WSMkwPkMABKjktC/nlm1GVrWPoc6KErHyITf9Wd5xEUE0Qn1HpeVCLXyPcpQN7gSE6LppeVfc2Q54M+o10bUPrKEOvEAstksxI6kih6Wxt8nTbn9hCcoNOk9ugTwfYjpLIomjVhUk0q1NuuFNoaSD5ZuYfzOjrVEsN7w7P7k///0wrI=
  app: unittest-travis-heroku
  on:
    repo: nagck/unittest-travis-heroku
  skip_cleanup: 'true'
